# Generated by Django 4.1.2 on 2022-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenter', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=30)),
                ('category', models.IntegerField(blank=True, choices=[(1, '技術系'), (2, '業務系'), (3, 'ビジネススキル'), (4, 'その他')], null=True)),
                ('detail', models.TextField()),
                ('presented_at', models.DateField()),
                ('is_presented', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'presentations',
            },
        ),
    ]
